name: edo-paper
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - scikit-learn
  - scipy
  - pip:
    - alphashape
    - descartes==1.1.0
    - edo==0.3.5
    - edolab==0.0.5
    - shapely>=1.2
